### ISSUE TITLE
Use of result in Polynomial.interpolate

### ISSUE THREAD

**Issue by hermanbergwerf** [thelonious/kld-polynomial#5]
I was wondering why result is here: https://github.com/thelonious/kld-polynomial/blob/c70584ed1cb434a373c85129a4a39480907e70bf/lib/Polynomial.js#L38.
It does not do anything in the code. (values are stored there but not retrieved). Maybe if result is set its content needs to be returned in the end?

**Comment by thelonious** [comment]
Hmm, you're going to make me have to remember something I wrote 13 years ago :). That does look suspicious to me. Give me a little bit to see if I can find the original references I used for that code. That should refresh my memory so I can respond to this properly.

Thanks for pointing this out!

**Comment by thelonious** [comment]
OK, finally getting around to looking deeper into this. This code comes from "Numerical Recipes in C", specifically their `polint` function in section 3.1. In their code, that is an error condition. If I remember correctly, I was trying to avoid throwing in any of this code. I wasn't sure what to return in this case and apparently I forgot to fix that. I think for now, it makes sense to return `null` or to `throw`. I prefer the former.

**Comment by thelonious** [comment]
And of course, I look at the rest of my code and I see a `throw` in that method when getting bad argument types :)
